# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ytq/codeField/exercise/PROJ_11_14/LeNet_Accelerator/LeNet_Accelerator.srcs/sources_1/ip/inp_mem_2/inp_mem.xci
# IP: The module: 'inp_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ytq/codeField/exercise/PROJ_11_14/LeNet_Accelerator/LeNet_Accelerator.gen/sources_1/ip/inp_mem_2/inp_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inp_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/ytq/codeField/exercise/PROJ_11_14/LeNet_Accelerator/LeNet_Accelerator.srcs/sources_1/ip/inp_mem_2/inp_mem.xci
# IP: The module: 'inp_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ytq/codeField/exercise/PROJ_11_14/LeNet_Accelerator/LeNet_Accelerator.gen/sources_1/ip/inp_mem_2/inp_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inp_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
