# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lenet.xdc

# IP: ip/wgt_mem/wgt_mem.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wgt_mem || ORIG_REF_NAME==wgt_mem} -quiet] -quiet
